### PR TITLE
Ensure zxcvbn is loaded before using it

### PR DESCRIPTION
**Pull request by dignifiedquire**
We had some issues where fast filling of the input (aka autofill) was triggering and `undefined is not a function` error on the usage of `zxcvbn`. This should avoid this.

### CODE REVIEW

**Comment by seethroughdev** [comment]
Looks good thanks.  Will merge along with a couple other updates tonight/tomorrow.

**Comment by seethroughdev** [comment]
I added the check manually while fixing a couple other things before compiling, so it should be good to go.  Thanks again.

**Comment by seethroughdev** [comment]
Will bump version in npm tomorrow.

**Comment by seethroughdev** [comment]
npm bumped.

**Comment by dignifiedquire** [comment]
Thanks

**Pull request closed without merging**
