### PR TITLE
On change

### PR DESCRIPTION
**Pull request by dignifiedquire**
Hey, 
thanks for the nice component, as I'm integrating this with other form solutions I wanted to a way to react on every input change, so I've added proper handling of `onChange` so the main `onChange` handler does not get overridden.

### CODE REVIEW

**Comment by seethroughdev** [comment]
Thanks @Dignifiedquire glad you found some use for it.  I'll look through the PR tomorrow for sure.  

Just curious, what was the babel 'experimental flag' for?

**Comment by dignifiedquire** [comment]
To allow for the object spread operator `var {onChange, ...props} = this.props`

**Comment by seethroughdev** [comment]
Gotcha.  Thanks.

**Comment by seethroughdev** [comment]
Totally on board with this, thanks for doing it.  Can you change the PR to incoming/pr1 branch instead of master?

**Pull request closed without merging**
